# Generated by Django 5.0.2 on 2024-02-24 11:49

import app.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiKeys",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "key",
                    models.CharField(default=uuid.uuid4, max_length=100, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Data",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("_title", models.CharField(max_length=100)),
                ("_created_at", models.DateTimeField(auto_now_add=True)),
                ("_updated_at", models.DateTimeField(auto_now=True)),
                ("_published_at", models.DateTimeField(blank=True, null=True)),
                ("value", models.JSONField(default=dict)),
                ("_model", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("icon", models.ImageField(blank=True, null=True, upload_to="icon/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("standard", "Standard"),
                            ("premium", "Premium"),
                        ],
                        default="free",
                        max_length=100,
                    ),
                ),
                (
                    "plan_created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "plan_updated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Access",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("createad_at", models.DateTimeField(auto_now_add=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        default=app.models.get_default_api_key,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access",
                        to="app.apikeys",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="app.post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublishmentStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Review"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=100,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "_data",
                    models.ForeignKey(
                        default=app.models.get_default_data,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status",
                        to="app.data",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Space",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        default=app.models.get_default_organization,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spaces",
                        to="app.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="data",
            name="space",
            field=models.ForeignKey(
                default=app.models.get_default_space,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data",
                to="app.space",
            ),
        ),
        migrations.AddField(
            model_name="apikeys",
            name="space",
            field=models.ForeignKey(
                default=app.models.get_default_space,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to="app.space",
            ),
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership",
                        to="app.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=app.models.get_default_user,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership",
                        to="app.user",
                    ),
                ),
            ],
        ),
    ]
