BEGIN;
--
-- Create model ApiKeys
--
CREATE TABLE "app_apikeys" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "key" varchar(100) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL);
--
-- Create model Associate
--
CREATE TABLE "app_associate" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "icon" varchar(100) NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "plan" varchar(100) NOT NULL, "plan_created_at" timestamp with time zone NOT NULL, "plan_updated_at" timestamp with time zone NOT NULL);
--
-- Create model Data
--
CREATE TABLE "app_data" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "_title" varchar(100) NOT NULL, "_created_at" timestamp with time zone NOT NULL, "_updated_at" timestamp with time zone NOT NULL, "_published_at" timestamp with time zone NOT NULL, "value" jsonb NOT NULL);
--
-- Create model Access
--
CREATE TABLE "app_access" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "createad_at" timestamp with time zone NOT NULL, "api_key_id" integer NOT NULL);
--
-- Create model PublishmentStatus
--
CREATE TABLE "app_publishmentstatus" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "status" varchar(100) NOT NULL, "updated_at" timestamp with time zone NOT NULL, "data_id" integer NOT NULL);
--
-- Create model Space
--
CREATE TABLE "app_space" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "associate_id" integer NOT NULL);
--
-- Add field space to apikeys
--
ALTER TABLE "app_apikeys" ADD COLUMN "space_id" integer DEFAULT 1 NOT NULL CONSTRAINT "app_apikeys_space_id_50ca1df5_fk_app_space_id" REFERENCES "app_space"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "app_apikeys_space_id_50ca1df5_fk_app_space_id" IMMEDIATE;
ALTER TABLE "app_apikeys" ALTER COLUMN "space_id" DROP DEFAULT;
--
-- Create model Structure
--
CREATE TABLE "app_structure" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "description" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "space_id" integer NOT NULL);
--
-- Add field structure to data
--
ALTER TABLE "app_data" ADD COLUMN "structure_id" integer DEFAULT 1 NOT NULL CONSTRAINT "app_data_structure_id_ac3f8fe4_fk_app_structure_id" REFERENCES "app_structure"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "app_data_structure_id_ac3f8fe4_fk_app_structure_id" IMMEDIATE;
ALTER TABLE "app_data" ALTER COLUMN "structure_id" DROP DEFAULT;
--
-- Create model User
--
CREATE TABLE "app_user" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL);
CREATE TABLE "app_user_associate" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" integer NOT NULL, "associate_id" integer NOT NULL);
ALTER TABLE "app_access" ADD CONSTRAINT "app_access_api_key_id_3c2a9e5e_fk_app_apikeys_id" FOREIGN KEY ("api_key_id") REFERENCES "app_apikeys" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_access_api_key_id_3c2a9e5e" ON "app_access" ("api_key_id");
ALTER TABLE "app_publishmentstatus" ADD CONSTRAINT "app_publishmentstatus_data_id_707a650b_fk_app_data_id" FOREIGN KEY ("data_id") REFERENCES "app_data" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_publishmentstatus_data_id_707a650b" ON "app_publishmentstatus" ("data_id");
ALTER TABLE "app_space" ADD CONSTRAINT "app_space_associate_id_06494b39_fk_app_associate_id" FOREIGN KEY ("associate_id") REFERENCES "app_associate" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_space_associate_id_06494b39" ON "app_space" ("associate_id");
CREATE INDEX "app_apikeys_space_id_50ca1df5" ON "app_apikeys" ("space_id");
ALTER TABLE "app_structure" ADD CONSTRAINT "app_structure_space_id_d5668832_fk_app_space_id" FOREIGN KEY ("space_id") REFERENCES "app_space" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_structure_space_id_d5668832" ON "app_structure" ("space_id");
CREATE INDEX "app_data_structure_id_ac3f8fe4" ON "app_data" ("structure_id");
ALTER TABLE "app_user_associate" ADD CONSTRAINT "app_user_associate_user_id_associate_id_82427623_uniq" UNIQUE ("user_id", "associate_id");
ALTER TABLE "app_user_associate" ADD CONSTRAINT "app_user_associate_user_id_b608479c_fk_app_user_id" FOREIGN KEY ("user_id") REFERENCES "app_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_user_associate" ADD CONSTRAINT "app_user_associate_associate_id_71cb28b3_fk_app_associate_id" FOREIGN KEY ("associate_id") REFERENCES "app_associate" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_user_associate_user_id_b608479c" ON "app_user_associate" ("user_id");
CREATE INDEX "app_user_associate_associate_id_71cb28b3" ON "app_user_associate" ("associate_id");
COMMIT;
