# Generated by Django 5.0.2 on 2024-02-16 01:27

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="structure",
            field=models.ForeignKey(
                default=app.models.get_default_structure,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data",
                to="app.structure",
            ),
        ),
        migrations.AlterField(
            model_name="structure",
            name="space",
            field=models.ForeignKey(
                default=app.models.get_default_space,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="structures",
                to="app.space",
            ),
        ),
    ]
