# Generated by Django 5.0.2 on 2024-02-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_apikeys_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="associate",
        ),
        migrations.AddField(
            model_name="associate",
            name="user",
            field=models.ManyToManyField(related_name="associates", to="app.user"),
        ),
    ]
