# Generated by Django 5.0.2 on 2024-02-16 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_data_structure_alter_structure_space"),
    ]

    operations = [
        migrations.RenameField(
            model_name="data",
            old_name="created_at",
            new_name="_created_at",
        ),
        migrations.RenameField(
            model_name="data",
            old_name="published_at",
            new_name="_published_at",
        ),
        migrations.RenameField(
            model_name="data",
            old_name="title",
            new_name="_title",
        ),
        migrations.RenameField(
            model_name="data",
            old_name="updated_at",
            new_name="_updated_at",
        ),
    ]
