# Generated by Django 5.0.2 on 2024-02-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_post_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="_published_at",
            field=models.DateTimeField(),
        ),
    ]
