# Generated by Django 5.0.2 on 2024-02-19 07:31

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_user_associate_associate_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apikeys",
            old_name="key",
            new_name="api_key",
        ),
        migrations.RemoveField(
            model_name="apikeys",
            name="space",
        ),
        migrations.AddField(
            model_name="apikeys",
            name="associate",
            field=models.ForeignKey(
                default=app.models.get_default_associate,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to="app.associate",
            ),
        ),
    ]
