import pytest

from app.models import Access, ApiKeys


class TestApiKeysModel:
    @pytest.mark.django_db
    def test_key_is_unique(self):
        api_key1 = ApiKeys.objects.create()
        api_key2 = ApiKeys.objects.create()
        assert api_key1.key != api_key2.key

    @pytest.mark.django_db
    def test_key_is_autogenerated(self):
        api_key = ApiKeys.objects.create()
        assert api_key.key is not None


class TestAccessModel:
    @pytest.mark.django_db
    def test_default_api_key(self):
        api_key = ApiKeys.objects.create()
        access = Access.objects.create()
        assert access.api_key.id == api_key.id

    @pytest.mark.django_db
    def test_generate_new_api_key(self):
        Access.objects.all().delete()
        ApiKeys.objects.all().delete()
        access = Access.objects.create()
        assert access.api_key is not None
