BEGIN;
--
-- Create model Data
--
CREATE TABLE "app_data" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(100) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "published_at" timestamp with time zone NOT NULL, "value" jsonb NOT NULL);
--
-- Create model Plan
--
CREATE TABLE "app_plan" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL);
--
-- Create model Space
--
CREATE TABLE "app_space" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL);
--
-- Create model Usage
--
CREATE TABLE "app_usage" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "data_transported" integer NOT NULL, "api_requested" integer NOT NULL, "createad_at" timestamp with time zone NOT NULL);
--
-- Create model PublishmentStatus
--
CREATE TABLE "app_publishmentstatus" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "status" varchar(100) NOT NULL, "updated_at" timestamp with time zone NOT NULL, "data_id" integer NOT NULL);
--
-- Create model Structure
--
CREATE TABLE "app_structure" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "description" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "space_id" integer NOT NULL);
--
-- Add field structure to data
--
ALTER TABLE "app_data" ADD COLUMN "structure_id" integer DEFAULT 1 NOT NULL CONSTRAINT "app_data_structure_id_ac3f8fe4_fk_app_structure_id" REFERENCES "app_structure"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "app_data_structure_id_ac3f8fe4_fk_app_structure_id" IMMEDIATE;
ALTER TABLE "app_data" ALTER COLUMN "structure_id" DROP DEFAULT;
--
-- Create model User
--
CREATE TABLE "app_user" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "plan_id" bigint NOT NULL);
--
-- Create model Associate
--
CREATE TABLE "app_associate" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "icon" varchar(100) NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "space_id" integer NULL, "usage_id" bigint NULL, "member_id" integer NOT NULL);
ALTER TABLE "app_publishmentstatus" ADD CONSTRAINT "app_publishmentstatus_data_id_707a650b_fk_app_data_id" FOREIGN KEY ("data_id") REFERENCES "app_data" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_publishmentstatus_data_id_707a650b" ON "app_publishmentstatus" ("data_id");
ALTER TABLE "app_structure" ADD CONSTRAINT "app_structure_space_id_d5668832_fk_app_space_id" FOREIGN KEY ("space_id") REFERENCES "app_space" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_structure_space_id_d5668832" ON "app_structure" ("space_id");
CREATE INDEX "app_data_structure_id_ac3f8fe4" ON "app_data" ("structure_id");
ALTER TABLE "app_user" ADD CONSTRAINT "app_user_plan_id_2f8353fc_fk_app_plan_id" FOREIGN KEY ("plan_id") REFERENCES "app_plan" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_user_plan_id_2f8353fc" ON "app_user" ("plan_id");
ALTER TABLE "app_associate" ADD CONSTRAINT "app_associate_space_id_ef5b5216_fk_app_space_id" FOREIGN KEY ("space_id") REFERENCES "app_space" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_associate" ADD CONSTRAINT "app_associate_usage_id_72ce1db7_fk_app_usage_id" FOREIGN KEY ("usage_id") REFERENCES "app_usage" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_associate" ADD CONSTRAINT "app_associate_member_id_8be98df7_fk_app_user_id" FOREIGN KEY ("member_id") REFERENCES "app_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_associate_space_id_ef5b5216" ON "app_associate" ("space_id");
CREATE INDEX "app_associate_usage_id_72ce1db7" ON "app_associate" ("usage_id");
CREATE INDEX "app_associate_member_id_8be98df7" ON "app_associate" ("member_id");
COMMIT;
