name: pytest

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade-pip
          pip install pytest black ruff
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with ruff
        run: ruff lint

      - name: Test with pytest
        run: |
          set -e
          CHANGED_FILES=$(git diff --name-only origin/main)
          if [ -n "$CHANGED_FILES" ]; then
            pytest $CHANGED_FILES
          else
            pytest
          fi
